/**
 * Mapeo de código ISO 3166-1 alpha-2 (ej: AR, CL) a nombres exactos del single select de Airtable.
 * Usado para derivar el país del prefijo telefónico de forma anónima.
 *
 * PAIS_SIN_ESPECIFICAR: valor cuando el prefijo no coincide. Debe existir esta opción en el single select de Airtable.
 */
export const PAIS_SIN_ESPECIFICAR = "—";

export const COUNTRY_CODE_TO_AIRTABLE: Record<string, string> = {
  AR: "Argentina",
  BO: "Bolivia",
  BR: "Brasil",
  CL: "Chile",
  CO: "Colombia",
  CR: "Costa Rica",
  EC: "Ecuador",
  GT: "Guatemala",
  MX: "Mexico",
  NI: "Nicaragua",
  PA: "Panama",
  PY: "Paraguay",
  PE: "Peru",
  UY: "Uruguay",
  VE: "Venezuela",
  ES: "España",
  PT: "Portugal",
  DE: "Alemania",
  FR: "Francia",
  IT: "Italia",
  GB: "Reino Unido",
  AD: "Andorra",
  AT: "Austria",
  BE: "Bélgica",
  BG: "Bulgaria",
  HR: "Croacia",
  CY: "Chipre",
  CZ: "Chequia",
  DK: "Dinamarca",
  SK: "Eslovaquia",
  SI: "Eslovenia",
  EE: "Estonia",
  FI: "Finlandia",
  GR: "Grecia",
  HU: "Hungría",
  IE: "Irlanda",
  LV: "Letonia",
  LT: "Lituania",
  LU: "Luxemburgo",
  MT: "Malta",
  NL: "Países Bajos",
  PL: "Polonia",
  RO: "Rumanía",
  SE: "Suecia",
  CH: "Suiza",
  NO: "Noruega",
  IS: "Islandia",
  LI: "Liechtenstein",
  AL: "Albania",
  AM: "Armenia",
  AZ: "Azerbaiyán",
  BY: "Bielorrusia",
  BA: "Bosnia y Herzegovina",
  GE: "Georgia",
  XK: "Kosovo",
  MD: "Moldavia",
  ME: "Montenegro",
  MK: "Macedonia del Norte",
  RU: "Rusia",
  SM: "San Marino",
  RS: "Serbia",
  UA: "Ucrania",
  VA: "Vaticano",
  AF: "Afghanistan",
  DZ: "Algeria",
  AO: "Angola",
  AG: "Antigua and Barbuda",
  AU: "Australia",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BZ: "Belize",
  BJ: "Benin",
  BT: "Bhutan",
  BW: "Botswana",
  BN: "Brunei",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CF: "Central African Republic",
  TD: "Chad",
  CN: "China",
  KM: "Comoros",
  CG: "Congo (Congo-Brazzaville)",
  CU: "Cuba",
  CD: "Democratic Republic of the Congo",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  SZ: "Eswatini (fmr. \"Swaziland\")",
  ET: "Ethiopia",
  FJ: "Fiji",
  GA: "Gabon",
  GM: "Gambia",
  GH: "Ghana",
  GD: "Grenada",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IL: "Israel",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MH: "Marshall Islands",
  MR: "Mauritania",
  MU: "Mauritius",
  FM: "Micronesia",
  MN: "Mongolia",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar (formerly Burma)",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NZ: "New Zealand",
  NE: "Niger",
  NG: "Nigeria",
  KP: "North Korea",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine State",
  PG: "Papua New Guinea",
  PH: "Philippines",
  QA: "Qatar",
  RW: "Rwanda",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SO: "Somalia",
  ZA: "South Africa",
  KR: "South Korea",
  SS: "South Sudan",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TV: "Tuvalu",
  UG: "Uganda",
  AE: "United Arab Emirates",
  US: "United States of America",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VN: "Vietnam",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};
